version: 2

refs:
  container: &container
    docker:
      - image: node:8.11
    working_directory: ~/repo

jobs:
  all:
    <<: *container
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Versions
          command: node -v && npm -v && yarn -v
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Test
          command: yarn test
      - run:
          name: Lint
          command: yarn lint

  master:
    <<: *container
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Versions
          command: node -v && npm -v && yarn -v
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Test
          command: yarn test
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Release
          command: yarn release
      - run:
          name: Post to GitHub
          command: |
            npx cross-ci :run \
                npx commit-status success Version "'\${PROJECT_VERSION}'"
      - run:
          name: Post to Slack
          command: npx ci-scripts slack
      - run:
          name: Post to Slack on FAILURE
          command:
            'npx ci-scripts slack --eval --channel="devchat" --text="*\${PROJECT_NAME}* master build failed: \${BUILD_URL}" --icon_emoji=tired_face'
          when: on_fail

workflows:
  version: 2
  all:
    jobs:
      - all:
          filters:
            branches:
              ignore:
                - master
  master:
    jobs:
      - master:
          filters:
            branches:
              only: master
